spring.application.name=flows-camunda-7
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
spring.main.allow-bean-definition-overriding=true


operaton.bpm.database.schema-update=true
operaton.bpm.admin-user.id=demo
operaton.bpm.admin-user.password=demo
operaton.bpm.admin-user.firstName=Demo
operaton.bpm.filter.create=All tasks
operaton.bpm.webapp.application-path=/operaton
operaton.bpm.webapp.index-redirect-enabled=false

# Disable Vaadin dev mode to avoid frontend build issues
vaadin.productionMode=false
vaadin.exclude-urls=/operaton/**, /engine-rest/**
